### ISSUE TITLE
v2.4.2 breaks osc on external players

### ISSUE THREAD

**Issue by Bestfast** [jellyfin/jellyfin-mpv-shim#321] opened 2023-02-25 07:52 UTC
**Describe the bug**
As title says, no osc is showing with 2.4.2. Reverting to 2.2.0 I can see it.
Tried with mpv.net with https://github.com/maoiscat/mpv-osc-modern/

**Comment by iwalton3** [comment] 2023-02-25 15:33
https://github.com/jellyfin/jellyfin-mpv-shim/issues/320

Should be a duplicate of the issue above

**Comment by iwalton3** [comment] 2023-02-25 16:42
Also would you like me to port the MPV Shim trickplay previews to work with that specific OSC?

**Comment by Bestfast** [comment] 2023-02-25 16:53
> #320
> 
> Should be a duplicate of the issue above

sorry, didn't check for previous issues. my bad.



> Also would you like me to port the MPV Shim trickplay previews to work with that specific OSC?

if you could that would help a lot, feel free to close as a duplicate though

**Comment by iwalton3** [comment] 2023-02-25 19:29
Here is a version of that osc which uses my thumbnail seek provider: https://github.com/iwalton3/mpv-osc-modern/

**Comment by iwalton3** [comment] 2023-02-25 20:20
It you install the latest CI version the above script has been tested and is known to work. Follow the directions in the README. Specifically you need to configure an alternate OSC and install the font.

**Closed by iwalton3** 2023-02-25 20:20 UTC
Labels: bug

**Comment by iwalton3** [comment] 2023-02-25 23:08
Update 2: I added a compatibility layer so that Jellyfin MPV Shim will do trickplay with any third-party OSC which works with https://github.com/po5/thumbfast.

To do this, just download one of the OSCs, place it in the scripts folder, and disable the `thumbnail_osc_builtin` option.
